# Compatible with `prek` and `pre-commit`, but this repo uses `prek`.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      # Python-specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/crate-ci/typos
    rev: v1.46.2
    hooks:
      - id: typos
        args: []

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run ty check quantinuum_qircheck tests
        language: system
        pass_filenames: false
